apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: mongodb
        tier: backend
        track: stable
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.dbPass }}
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.dbUser }}
        image: mongo:4.1.8-xenial
        name: mongodb
        ports:
          - name: http01
            containerPort: 27017
            protocol: TCP

        resources: {}
      restartPolicy: Always
status: {}
