apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "mongodb.fullname" . }}
  labels:
    app: {{ template "mongodb.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "mongodb.fullname" . }}
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: {{ template "mongodb.fullname" . }}
        tier: backend
        track: stable
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.dbPass }}
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.dbUser }}
        image: {{ .Values.dbimage }}:{{ .Values.dbimageTag }}
        name: mongodb
        ports:
          - name: http01
            containerPort: 27017
            protocol: TCP

        resources: {}
      restartPolicy: Always
status: {}
