apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  selector:
    app: mongo-express
    tier: frontend
    track: stable
  type: NodePort
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: mongo-express
    tier: frontend
    track: stable
status:
  loadBalancer: {}
