apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongo-express.fullname" . }}
spec:
  selector:
    app: {{ template "mongo-express.fullname" . }}
    tier: frontend
    track: stable
  type: {{ .Values.deployType }}
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: {{ template "mongo-express.fullname" . }}
    tier: frontend
    track: stable
status:
  loadBalancer: {}
